[http]
listen = "[::]:4000" #  "127.0.0.1:4000" # 监听所有 ip的 8888 端口
#cors = false # 跨域

[Auth]
# JSON WEB TOKEN secret
# secret= "<jwt_secret>"
# static JWT token, superadmin, debuggger can use this token
# tokens = [""]

[Log]
# level = "warn"

[database]
url = "postgres://postgres:postgres@localhost/database"
# 最大连接数 (Default: 10)
max_connections = 10
# 连接超时时间 (Default: 30)
connect_timeout = 30
